# Root Project Information
sonar.projectKey=devai
sonar.projectName=devai
sonar.host.url=http://localhost:9000
#sonar.token=sqp_09957b425987715f3568e39ec7d6b0f7156fd86b

# Define comma-separated paths to all source and test roots
sonar.sources=apps/backend/src,apps/frontend/src
sonar.tests=apps/backend/src,apps/frontend/src,apps/frontend/tests

# Monorepo Glob Inclusions
sonar.test.inclusions=**/*.spec.ts

# Pass a comma-separated list of all generated coverage reports
sonar.javascript.lcov.reportPaths=apps/backend/coverage/lcov.info,apps/frontend/coverage/lcov.info