name: Deploy to Vercel

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:

env:
  PROJECT_NAME: devai
  ENVIRONMENT: test
  TF_VAR_project_name: devai
  TF_VAR_environment: test
  AUTOMATION: true
  AWS_EC2_METADATA_DISABLED: true
  AWS_PAGER: ""
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
  NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
  CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
  CLERK_JWT_KEY: ${{ secrets.CLERK_JWT_KEY }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  TF_VAR_aws_region: ${{ secrets.AWS_REGION }}  
  ADMIN_EMAIL: ${{ vars.ADMIN_EMAIL }}
  ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
  CUSTOMER_EMAIL: ${{ vars.CUSTOMER_EMAIL }}
  CUSTOMER_PASSWORD: ${{ secrets.CUSTOMER_PASSWORD }}

jobs:  
  lint-unit-test:
    name: Lint & Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
      
      - name: Unit Test 
        run: npm run test:unit      

  # integration-e2e-tests:
  #   name: Integration & E2E Testing
  #   runs-on: ubuntu-latest
  #   env:
  #     DATABASE_URL: postgresql://user:password@127.0.0.1:5432/dbname?schema=public
  #     DIRECT_URL: postgresql://user:password@127.0.0.1:5432/dbname?schema=public
  #     NEXT_PUBLIC_API_URL: http://127.0.0.1:3001/api/v1
  #     CORS_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v7

  #     - name: Setup Node
  #       uses: actions/setup-node@v6
  #       with:
  #         node-version: '24'
  #         cache: 'npm'

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Start Database
  #       run: docker compose up -d db

  #     - name: Gerar schema
  #       run: npm run prisma:generate --workspace=backend

  #     - name: Database Setup
  #       run: npm run db:reset
  #       working-directory: apps/backend

  #     - name: Integration Test 
  #       run: npm run test:integration

  #     - name: free port 
  #       run: npx --yes kill-port 3001 || true

  #     - name: Install Playwright Browsers
  #       run: npx playwright install chromium --with-deps
  #       working-directory: apps/frontend

  #     - name: Run Playwright tests
  #       run: npx playwright test --project=cicd
  #       working-directory: apps/frontend
        
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra/environments/test
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -input=false -no-color

      - name: Terraform Apply
        run: |
          terraform apply -input=false -auto-approve -no-color


  build-deploy-frontend:
    name: Build & Deploy Frontend(Vercel)
    needs: [lint-unit-test, terraform]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    env:
      VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ENV: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') && 'production' || 'preview' }}
      VERCEL_BUILD_ARG: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') && '--prod' || '' }}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v7

      - name: Instalação do Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Instalar Dependências
        run: npm ci --workspace=frontend

      - name: Instalar Vercel CLI
        run: npm install --global vercel@50.26.1

      - name: Remove .vercel directory
        run: rm -rf .vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{ env.VERCEL_ENV }} --token=${{ env.VERCEL_TOKEN }} --scope=${{ env.VERCEL_ORG_ID }}

      - name: Build Project Artifacts
        run: vercel build ${{ env.VERCEL_BUILD_ARG }} --token=${{ env.VERCEL_TOKEN }} --scope=${{ env.VERCEL_ORG_ID }}

      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: |
          vercel deploy --prebuilt ${{ env.VERCEL_BUILD_ARG }} --token=${{ env.VERCEL_TOKEN }} --scope=${{ env.VERCEL_ORG_ID }} > deployment-url.txt
          echo "DEPLOYMENT_URL=$(cat deployment-url.txt)" >> $GITHUB_OUTPUT

      - name: Notificação de Status
        if: always()
        run: |
          echo "Status do Deploy: ${{ job.status }}"
          echo "URL: ${{ steps.deploy.outputs.DEPLOYMENT_URL }}"
     
  build-deploy-backend:
    name: Build & Deploy Backend (Vercel)
    needs: [lint-unit-test, terraform]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    env:
      VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ vars.VERCEL_BACKEND_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ENV: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') && 'production' || 'preview' }}
      VERCEL_BUILD_ARG: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') && '--prod' || '' }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DIRECT_URL: ${{ secrets.DIRECT_URL }}
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v7

      - name: Instalação do Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Instalar Dependências
        run: npm ci --workspace=backend

      - name: Instalar Vercel CLI
        run: npm install --global vercel@50.26.1

      - name: Remove .vercel directory
        run: rm -rf .vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{ env.VERCEL_ENV }} --token=${{ env.VERCEL_TOKEN }} --scope=${{ env.VERCEL_ORG_ID }}

      - name: Build Project Artifacts
        run: vercel build ${{ env.VERCEL_BUILD_ARG }} --token=${{ env.VERCEL_TOKEN }} --scope=${{ env.VERCEL_ORG_ID }}

      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: |
          vercel deploy --prebuilt ${{ env.VERCEL_BUILD_ARG }} --token=${{ env.VERCEL_TOKEN }} --scope=${{ env.VERCEL_ORG_ID }} > deployment-url.txt
          echo "DEPLOYMENT_URL=$(cat deployment-url.txt)" >> $GITHUB_OUTPUT

      - name: Notificação de Status
        if: always()
        run: |
          echo "Status do Deploy: ${{ job.status }}"
          echo "URL: ${{ steps.deploy.outputs.DEPLOYMENT_URL }}"
